# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('filetype', models.CharField(max_length=128)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('updated_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
