# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filetype',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
